# Generated by Django 5.0.6 on 2024-05-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('snippet', models.CharField(max_length=250)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
